import Footer from "@/component/footer/FooterSeller";
import { FiAlignJustify } from "react-icons/fi";

import Header from "@/component/header/Header";
import global from "@/stylesheet/global.module.css";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* heade */}
        <Header />

        {/* navbar */}

        <div
          className={`grid grid-flow-col grid-rows-1 gap-0  p-5 bg-[#FFC6E3]`}
        >
          <div className={`${global.tri_equal} col-span-2`}>
            <FiAlignJustify />
          </div>
          {/*  */}
          <div className="col-span-6 flex justify-center items-center ">
            <ul className="flex space-x-4">
              <li className={`${global.subject_card}   text-white`}>
                <Link className={`${global.subject_card12}`} href="/">
                  Home
                </Link>
              </li>

              <li className={`${global.subject_card}   text-white`}>
                <Link href="/buyer/Division">Division</Link>
              </li>
              <li className={`${global.subject_card}   text-white`}>
                <Link href="/buyer/Rural_Handicrafts">Rural Handicrafts</Link>
              </li>

              <li className={`${global.subject_card}   text-white`}>
                <Link href="/buyer/Rural_Machinery">Rural Machinery</Link>
              </li>

              <li className={`${global.subject_card}   text-white`}>
                <Link href="/buyer/Festivals">Festivals</Link>
              </li>

              <li className={`${global.subject_card}   text-white`}>
                <Link href="/buyer/Traditional_Foods">Traditional Food</Link>
              </li>

              <li className={`${global.subject_card}   text-white`}>
                <Link href="/buyer/Traditional_Cloth">Traditional Cloth</Link>
              </li>
            </ul>
          </div>
        </div>

        {/* navbar */}

        {children}
        {/* footer */}
        <Footer />
      </body>
    </html>
  );
}
